on_rails/calculator_app/config/routes.rb
CalculatorApp::Application.routes.draw do
  root 'calculator#index'
  resources :calculator, only: [:index, :create]

end

on_rails/calculator_app/app/models/calculator.rb
require 'redis-objects'
require 'redis-objects'
require 'dm-core'
require 'dm-redis-adapter'

class InvalidPolishExpression < StandardError
  def initialize(msg)
    @message = msg
  end
end

class NotSupportedInputException < StandardError
    def initialize(msg)
      @message = msg
    end
end

class Calculator
  
	include Redis::Objects
  include DataMapper::Resource

	property :id, Serial  
  
  value :param
  list :storage, :expiration => 1.hour, :marshal => true
  
  @@add = lambda{|a,b| a+b }
  @@subtract = lambda{|a,b| b-a }
  @@multiply = lambda{|a,b| a*b }
  @@divide = lambda{|a,b| b.to_f/a.to_f }
  @@modulus = lambda{|a,b| a%b }
  
  @@operator_map = {
    "+" => @@add,
    "-" => @@subtract,
    "*" => @@multiply,
    "/" => @@divide,
    "%" => @@modulus
  }

  def initialize
    #@storage and @param.value
  end

  def input(param)
    raise TypeError, "Nil is not accepeted" if param.nil?
    @param.value = param.to_s.strip()
    if sanitize
      return process_input()
    end
    @param.value = nil
    raise NotSupportedInputException.new("The input #{@param.value} is not supported")
  end

  def is_operable?
    @storage.length >= 2
  end

  def process_input
    if @@operator_map.include?(@param.value)
      if not is_operable?
        @param.value = nil
        raise InvalidPolishExpression.new("The polish expression is invalid")
      end

      operator1 = @storage.pop.to_f
      operator2 = @storage.pop.to_f
      operator = @@operator_map[@param.value]
      result = operator.call(operator1, operator2)
      @storage << result
      return result
    else
      result = @param.value
      @storage << @param.value
    end

    return result
  end

  def sanitize
    return true if @@operator_map.include?(@param.value)

    begin
      @param.value = Integer(@param.value)
      return true
    rescue ArgumentError
      begin
        @param.value = Float(@param.value)
        return true
      rescue ArgumentError
      end
    end
    return false
  end
  
  private :is_operable?, :process_input, :sanitize

end

on_rails/calculator_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

on_rails/calculator_app/app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  def index
    @id = SecureRandom.hex(4)
  end

  def create
    @c = Calculator.get(params[:calculator][:id])
    if not @c
      @c = Calculator.new
      @c.id = params[:calculator][:id]
    @c.storage
    @c.param
    end

    begin
      @success = true
      @msg = @c.input(params[:calculator][:param]) 
    rescue Exception => e
      @success = false
      @msg = e.message
    end
   
    render :json => {:success => @success, :result=>@msg}
  end

  def calculator_params
    params.requier(:calculator).permit(:id, :param)
  end
end

on_rails/calculator_app/app/helpers/application_helper.rb
module ApplicationHelper
end

on_rails/calculator_app/app/helpers/calculator_helper.rb
module CalculatorHelper
end

on_rails/calculator_app/app/views/calculator/create.html.erb
<h1>Calculator#create</h1>
<p>Find me in app/views/calculator/create.html.erb</p>

on_rails/calculator_app/app/views/calculator/index.html.erb
<script>
$.calc_id = "<%= @id %>";

jQuery(function($, undefined) {
  $('#terminal').terminal(function(command, term) {
    if (command !== '') {
      try {
        $.ajax({
          method: 'POST',
          dataType: 'json',
          url: '<%= calculator_index_path %>',
          async: false,
          data: {'calculator[id]': $.calc_id, 'calculator[param]': command},
          success: function(data){
            if (data.success) {
              term.echo(data.result + "");
            }else{
              term.error(data.result);
            }},
          fail: function(){
            term.error("Failed to reach the calculator");
          }
        });

      } catch(e) {
        term.error(new String(e));
      }
    } else {
      term.echo('');
    }
  }, {
    greetings: 'PRN Calculator',
    name: 'js_demo',
    height: '400px',
    prompt: ' > '});
});
</script>

on_rails/calculator_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorApp</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header id="main">

      <pre id="sig">     

     ____  ____  __ _         ___   __   __     ___  _  _  __     __  ____  __  ____ 
    (  _ \(  _ \(  ( \       / __) / _\ (  )   / __)/ )( \(  )   / _\(_  _)/  \(  _ \
     )   / ) __//    /      ( (__ /    \/ (_/\( (__ ) \/ (/ (_/\/    \ )( (  O ))   /
    (__\_)(__)  \_)__)       \___)\_/\_/\____/ \___)\____/\____/\_/\_/(__) \__/(__\_)
                                               Created by : Scaria&lt;github.com/scaria&gt;  
      </pre>

    </header>

    <section>
      <article>
        <div id="terminal" class="terminal" style="height: 600px;">
          <div class="terminal-output">
            <%= yield %>
          </div>
        </div>
      </article>
    </section>
    <footer>
            <p id="copy">Credits: JQuery Terminal Emulator (<a href="http://terminal.jcubic.pl/" >link</a>, <a href="http://jcubic.pl/jakub-jankiewicz">Jakub Jankiewicz</a>)</p>
    </footer>

  </body>
</html>